server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 567cybtfboys
  profiles:
    # 多环境配置加载内容 dev/prod，不写就是默认 default 配置
    active: dev
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.203.1:8848 # 配置nacos地址
    sentinel:
      transport:
        dashboard: http://localhost:8080 # 配置 Sentinel dashboard 控制台服务地址
        port: 8719 # 默认8719端口，假如该端口被占用，会自动从 8719 开始依次加1，直到找到未被占用的端口
