server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.203.1:8848        #Nacos服务注册中心地址
  # ==========applicationName + druid-mysql8 driver===================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 567cybtfboys
  profiles:
    # 多环境配置加载内容 dev/prod，不写就是默认 default 配置
    active: dev
# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yunbocheng.springcloud.entities
  configuration:
    map-underscore-to-camel-case: true


# ========================seata===================
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.203.1:8848
      namespace: "" # 空字符串代表使用默认空间 public
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group # 事务组，由它获得TC服务的集群名称
  service:
    vgroup-mapping:
      default_tx_group: default # 事务组与TC服务集群的映射关系
  data-source-proxy-mode: AT

logging:
  level:
    io:
      seata: info