server:
  port: 83

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 567cybtfboys
  profiles:
    # 多环境配置加载内容 dev/prod，不写就是默认 default 配置
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.203.1:8848

# 消费者要去访问的服务名称(以nacos中的服务名为准)
service-url:
  nacos-user-service: http://nacos-provider-payment

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true