server:
  port: 8401

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 567cybtfboys
  profiles:
    # 多环境配置加载内容 dev/prod，不写就是默认 default 配置
    active: dev

  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.203.1:8848
    sentinel:
      transport:
        dashboard: http://localhost:8080 # 配置 Sentinel dashboard 控制台服务地址
        port: 8719 # 默认8719端口，假如该端口被占用，会自动从 8719 开始依次加1，直到找到未被占用的端口
      datasource: # Sentinel持久化配置
        ds1: # 就是自定义的key，也可以叫做限流类型等等
          nacos:
            server-addr: http://192.168.203.1:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 此处为流控规则
#        ds2: # 就是自定义的key，也可以叫做限流类型等等
#          nacos:
#            server-addr: http://192.168.203.1:8848
#            dataId: degrade
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: degrade # 此处为熔断规则