server:
  port: 9527

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 567cybtfboys
  profiles:
    # 多环境配置加载内容 dev/prod，不写就是默认 default 配置
    active: dev

  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-payment               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**
        - id: pay_routh2
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/pay/gateway/info/**
        - id: pay_routh3
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/pay/gateway/filter/**
            - MyPre=cyb
          filters:
            - AddRequestHeader=X-Request-chengyunbo, chengyunbo
            - AddRequestHeader=X-Request-cyb, cyb
